# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yash/python/pyqt/fifa_mgmt/fifa_basic.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 515)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 621, 451))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.home_tab = QtWidgets.QWidget()
        self.home_tab.setObjectName("home_tab")
        self.label_home = QtWidgets.QLabel(self.home_tab)
        self.label_home.setGeometry(QtCore.QRect(0, 0, 621, 411))
        font = QtGui.QFont()
        font.setFamily("Linux Libertine Initials O")
        font.setPointSize(18)
        self.label_home.setFont(font)
        self.label_home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_home.setFrameShape(QtWidgets.QFrame.Box)
        self.label_home.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_home.setText("")
        self.label_home.setPixmap(QtGui.QPixmap("1200px-Panoramic_santiago_bernabeu.jpg"))
        self.label_home.setAlignment(QtCore.Qt.AlignCenter)
        self.label_home.setObjectName("label_home")
        self.label = QtWidgets.QLabel(self.home_tab)
        self.label.setGeometry(QtCore.QRect(140, 20, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK JP")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.home_tab, "")
        self.Players_tab = QtWidgets.QWidget()
        self.Players_tab.setObjectName("Players_tab")
        self.tableView = QtWidgets.QTableView(self.Players_tab)
        self.tableView.setGeometry(QtCore.QRect(230, 30, 361, 341))
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(self.Players_tab)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 115, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.Players_tab)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 90, 115, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.Players_tab)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 150, 115, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.Players_tab)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 210, 115, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.Players_tab, "")
        self.Teams_tab = QtWidgets.QWidget()
        self.Teams_tab.setObjectName("Teams_tab")
        self.pushButton_5 = QtWidgets.QPushButton(self.Teams_tab)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 90, 115, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tableView_2 = QtWidgets.QTableView(self.Teams_tab)
        self.tableView_2.setGeometry(QtCore.QRect(230, 30, 361, 341))
        self.tableView_2.setObjectName("tableView_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.Teams_tab)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 30, 115, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.Teams_tab)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 210, 115, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.Teams_tab)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 150, 115, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.Teams_tab, "")
        self.Bookings = QtWidgets.QWidget()
        self.Bookings.setObjectName("Bookings")
        self.pushButton_9 = QtWidgets.QPushButton(self.Bookings)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 90, 115, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.tableView_3 = QtWidgets.QTableView(self.Bookings)
        self.tableView_3.setGeometry(QtCore.QRect(230, 30, 361, 341))
        self.tableView_3.setObjectName("tableView_3")
        self.pushButton_10 = QtWidgets.QPushButton(self.Bookings)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 30, 115, 30))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.Bookings)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 210, 115, 30))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.Bookings)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 150, 115, 30))
        self.pushButton_12.setObjectName("pushButton_12")
        self.tabWidget.addTab(self.Bookings, "")
        self.Matches_tab = QtWidgets.QWidget()
        self.Matches_tab.setObjectName("Matches_tab")
        self.pushButton_13 = QtWidgets.QPushButton(self.Matches_tab)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 90, 115, 30))
        self.pushButton_13.setObjectName("pushButton_13")
        self.tableView_4 = QtWidgets.QTableView(self.Matches_tab)
        self.tableView_4.setGeometry(QtCore.QRect(230, 30, 361, 341))
        self.tableView_4.setObjectName("tableView_4")
        self.pushButton_14 = QtWidgets.QPushButton(self.Matches_tab)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 30, 115, 30))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.Matches_tab)
        self.pushButton_15.setGeometry(QtCore.QRect(20, 210, 115, 30))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.Matches_tab)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 150, 115, 30))
        self.pushButton_16.setObjectName("pushButton_16")
        self.tabWidget.addTab(self.Matches_tab, "")
        self.Scorers_tab = QtWidgets.QWidget()
        self.Scorers_tab.setObjectName("Scorers_tab")
        self.label_3 = QtWidgets.QLabel(self.Scorers_tab)
        self.label_3.setGeometry(QtCore.QRect(-10, 0, 671, 631))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("fifa/20032336-0-image-m-42_1571743623584.jpg"))
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(self.Scorers_tab)
        self.tableWidget.setGeometry(QtCore.QRect(160, 50, 291, 271))
        self.tableWidget.setRowCount(20)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tabWidget.addTab(self.Scorers_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Football World Cup Managing tool"))
        self.label.setText(_translate("MainWindow", "FIFA Manager 1.01"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.home_tab), _translate("MainWindow", "Home"))
        self.pushButton.setText(_translate("MainWindow", "Insert"))
        self.pushButton_2.setText(_translate("MainWindow", "Remove"))
        self.pushButton_3.setText(_translate("MainWindow", "Update"))
        self.pushButton_4.setText(_translate("MainWindow", "View"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Players_tab), _translate("MainWindow", "Players"))
        self.pushButton_5.setText(_translate("MainWindow", "Remove"))
        self.pushButton_6.setText(_translate("MainWindow", "Insert"))
        self.pushButton_7.setText(_translate("MainWindow", "View"))
        self.pushButton_8.setText(_translate("MainWindow", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Teams_tab), _translate("MainWindow", "Teams"))
        self.pushButton_9.setText(_translate("MainWindow", "Remove"))
        self.pushButton_10.setText(_translate("MainWindow", "Insert"))
        self.pushButton_11.setText(_translate("MainWindow", "View"))
        self.pushButton_12.setText(_translate("MainWindow", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Bookings), _translate("MainWindow", "Bookings"))
        self.pushButton_13.setText(_translate("MainWindow", "Remove"))
        self.pushButton_14.setText(_translate("MainWindow", "Insert"))
        self.pushButton_15.setText(_translate("MainWindow", "View"))
        self.pushButton_16.setText(_translate("MainWindow", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Matches_tab), _translate("MainWindow", "Matches"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Scorers_tab), _translate("MainWindow", "Scorers"))


    def insert_func(self,table_name):
        # call insert function from backend
        print()


    def delete_func(self,table_name):
        # call delete func from backend
        return None



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
