create database fifa;

use fifa;

CREATE TABLE PLAYERS(
	NAME VARCHAR(255) PRIMARY KEY,
	COUNTRY VARCHAR(255),
	POSITION VARCHAR(255),
	AGE INT,
	HEIGHT INT,
	WEIGHT INT,
	RATING INT
	);

CREATE TABLE GOALS(
	PLAYER_NAME VARCHAR(255) PRIMARY KEY,
	GOALS INT,
	FOREIGN KEY (PLAYER_NAME) REFERENCES PLAYERS(NAME) ON DELETE CASCADE
	);

CREATE TABLE TEAMS(
	NAME VARCHAR(255) PRIMARY KEY,
	COUNTRY VARCHAR(255),
	CAPTAIN VARCHAR(255)
	);

CREATE TABLE MATCHES(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	TEAM1 VARCHAR(255),
	TEAM2 VARCHAR(255),
	LOCATION VARCHAR(255),
	MATCH_DATE DATETIME,
	FOREIGN KEY (TEAM1) REFERENCES TEAMS(NAME) ON DELETE CASCADE,
	FOREIGN KEY (TEAM2) REFERENCES TEAMS(NAME) ON DELETE CASCADE
	);

CREATE TABLE PLAYS_FOR(
	TEAM VARCHAR(255),
	PLAYER VARCHAR(255),
	PRIMARY KEY(TEAM,PLAYER),
	FOREIGN KEY (TEAM) REFERENCES TEAMS(NAME) ON DELETE CASCADE,
	FOREIGN KEY (PLAYER) REFERENCES PLAYERS(NAME) ON DELETE CASCADE
	);

CREATE TABLE BOOKINGS(
	PLAYER VARCHAR(255) PRIMARY KEY,
	YELLOW_CARDS INT,
	RED_CARDS INT,
	FOREIGN KEY (PLAYER) REFERENCES PLAYERS(NAME) ON DELETE CASCADE
	);

CREATE TABLE GOALS_MATCH(
	MATCH_ID INT,
	PLAYER VARCHAR(255),
	TEAM VARCHAR(255),
	NO_OF_GOALS INT,
	PRIMARY KEY(MATCH_ID,PLAYER,TEAM),
	FOREIGN KEY (PLAYER) REFERENCES PLAYERS(NAME) ON DELETE CASCADE,
	FOREIGN KEY (MATCH_ID) REFERENCES MATCHES(ID) ON DELETE CASCADE,
	FOREIGN KEY (TEAM) REFERENCES TEAMS(NAME) ON DELETE CASCADE
	);
